### ISSUE TITLE
yle-dl: 'idna<2.6,>=2.5' distribution was not found and is required by requests

### ISSUE THREAD

**Issue by ghost** [juippis/jps-gentoo#1]
yle-dl[youtube-dl] didn't work.
`emerge =dev-python/idna-2.5` and it started working. ~amd64 system

Kiitos siististä yle-dl ebuildista!

**Comment by ghost** [comment]
```
$ yle-dl https://areena.yle.fi/1-3823910
Traceback (most recent call last):
  File "/usr/bin/yle-dl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'idna<2.6,>=2.5' distribution was not found and is required by requests
```

**Comment by ghost** [comment]
Hmmm, apparently it was a Gentoo-wide problem with dev-python/requests and fixed/worked around with by [this commit](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c4086f489ef2a4b0b2af25ab81c7b7490db8428b). Sorry for being hasty
